name: CI/CD
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run biome:ci
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: oven-sh/setup-bun@v2
      - run: bun ci --production
      - run: bun run build
      - uses: actions/upload-artifact@v4
        with:
          path: .vercel/output
          include-hidden-files: true
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: [biome, build]
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          path: .vercel/output
      - run: npm install -g vercel
      - id: deploy
        run: |
          vercel deploy --prebuilt --prod --yes --token ${{ secrets.VERCEL_TOKEN }} > deploy.txt
          echo "url=$(cat deploy.txt)" >> $GITHUB_OUTPUT
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    needs: [biome, build]
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          path: .vercel/output
      - run: npm install -g vercel
      - id: deploy
        run: |
          vercel deploy --prebuilt --yes --token ${{ secrets.VERCEL_TOKEN }} > deploy.txt
          echo "url=$(cat deploy.txt)" >> $GITHUB_OUTPUT
