name: Playwright Tests
on:
  repository_dispatch:
    types:
      - vercel.deployment.ready

permissions:
  contents: read
  statuses: write

jobs:
  e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: vercel/repository-dispatch/actions/status@v1
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - uses: oven-sh/setup-bun@v2
      - run: bun ci && bunx playwright install --with-deps
      - run: bunx playwright test --reporter=github
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
          VERCEL_PROTECTION_BYPASS: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          if-no-files-found: 'ignore'
          retention-days: 30
