name: Playwright Tests
on:
  repository_dispatch:
    types:
      - vercel.deployment.ready
jobs:
  e2e:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - uses: oven-sh/setup-bun@v2
      - run: bun ci && bunx playwright install --with-deps
      - run: bun run test:e2e
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
          VERCEL_PROTECTION_BYPASS: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
      - uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: "Vercel - eventernote-tools: e2e"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
